### PR TITLE
CI: Update toolchain to ARC 2023.09-release

### PR DESCRIPTION
**Pull request by abrodkin**
Use ARC GNU Toolchain 2023.09-release for CI

### CODE REVIEW

**Comment by qwersem** [comment]
Hi @abrodkin, please check

**Comment by abrodkin** [comment]
@qwersem so it seems to work now, right? Could you please explain what was the problem and why it gets fixed with Ubuntu version update? Why did it use to work before with an older version of the host OS image?

**Comment by qwersem** [comment]
@abrodkin yes, linux is built inside ubuntu 22.04. It was a dependency problem.
[Here](https://github.com/foss-for-synopsys-dwc-arc-processors/linux/actions/runs/7461142990/job/20300663073#step:6:85) I ran the simple gcc test inside a Ubuntu_20.04 container and got the next error:
```
# ./${toolchain_prefix}-gcc -v
./arc-elf32-gcc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./arc-elf32-gcc)
./arc-elf32-gcc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./arc-elf32-gcc)
./arc-elf32-gcc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./arc-elf32-gcc)
```

**Comment by abrodkin** [comment]
Ah, OK I see now. So sometime in 2022 `ubuntu-latest` image got switched from 20.04 to 22.04, see https://github.com/actions/runner-images/issues/6399. And so unexpectedly for us https://github.com/foss-for-synopsys-dwc-arc-processors/arc-gnu-toolchain/actions started to use newer Ubuntu, because indeed we use `ubuntu-latest` in both the workflows, see:
* https://github.com/foss-for-synopsys-dwc-arc-processors/arc-gnu-toolchain/blob/master/.github/workflows/build-release.yml#L56
* https://github.com/foss-for-synopsys-dwc-arc-processors/arc-gnu-toolchain/blob/master/.github/workflows/build-toolchains.yml#L48

We didn't notice that because the last build from there we use here was made a year ago and apparently back in the day `ubuntu-latest` was till 20.04. So the mystery is now solved.

And I guess now we need to align build environments here and in https://github.com/foss-for-synopsys-dwc-arc-processors/arc-gnu-toolchain with one of the solutions:
 * Standardize on `ubuntu-latest` in both workflows
 * Use explicit version like `22.04`

@qwersem @yaroslavsadin what's your take on that? Anyway, whatever you decide, please submit a separate PR with the fix where necessary and then I'll rebase my branch on top of your change.

**Pull request merged**
